### GET /
GET http://localhost:5003




###
POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username": "testuser1",
    "password": "testpasswordd"
}




###

POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpasswordd"
}


### Fetch all todos endpoints(protected)
GET  http://localhost:5003/todos
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzc3MzkxMTExLCJleHAiOjE3Nzc0Nzc1MTF9.1Zf64d7vbTku0gY5qgdZ5swzH1vx09G2MjleS2Sb-wk 

##CREATES NEW TODOS
POST http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzc3MzkxMTExLCJleHAiOjE3Nzc0Nzc1MTF9.1Zf64d7vbTku0gY5qgdZ5swzH1vx09G2MjleS2Sb-wk 

{}

### update a todo
PUT http://localhost:5000/todos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzc3MzkxMTExLCJleHAiOjE3Nzc0Nzc1MTF9.1Zf64d7vbTku0gY5qgdZ5swzH1vx09G2MjleS2Sb-wk
Content-Type: application/json

{
    "completed":1
    
}
